# Generated by Django 3.0.1 on 2020-01-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_fbimostwanteddata_fbiofficer_informant_messages_most_wanted_alias_most_wanted_dateofbirth_most_wante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbiofficer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='informant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sent_by',
        ),
        migrations.DeleteModel(
            name='FBImostwanteddata',
        ),
        migrations.DeleteModel(
            name='FBIOfficer',
        ),
        migrations.DeleteModel(
            name='Informant',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Most_wanted_alias',
        ),
        migrations.DeleteModel(
            name='Most_wanted_dateofbirth',
        ),
        migrations.DeleteModel(
            name='Most_wanted_languages',
        ),
        migrations.DeleteModel(
            name='Most_wanted_photos',
        ),
        migrations.DeleteModel(
            name='Most_wanted_posters',
        ),
    ]
