# Generated by Django 3.0.1 on 2020-01-01 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0004_auto_20200101_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='most_wanted_dateofbirth',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5000)),
                ('message', models.CharField(max_length=500000)),
                ('is_read', models.BooleanField(default=False)),
                ('creation_date', models.DateField()),
                ('receive_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recieved', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
