# Generated by Django 3.0.1 on 2020-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_auto_20200101_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='caution',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='reward',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='warning',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
