# Generated by Django 3.0.1 on 2020-01-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_auto_20200101_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='build',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='eyes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='hair',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='height_max',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='height_min',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='place_ofbirth',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='race_raw',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='sex',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fbiofficer',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fbiofficer',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='informant',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='informant',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='most_wanted_languages',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
