# Generated by Django 3.0.1 on 2020-01-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_auto_20200101_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='caution',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
