# Generated by Django 3.0.1 on 2020-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_auto_20200102_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='caution',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='remarks',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='reward',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='fbimostwanteddata',
            name='warning',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='most_wanted_alias',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='most_wanted_photos',
            name='link',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='most_wanted_posters',
            name='link',
            field=models.URLField(max_length=5000),
        ),
    ]
